# Generated by Django 6.1.1 on 2026-09-21 04:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('game', models.CharField(choices=[('battleship', 'Batalha Naval'), ('chess', 'Xadrez'), ('coup', 'Coup')], max_length=32)),
                ('status', models.CharField(choices=[('configuring', 'Configurando'), ('in_progress', 'Em andamento'), ('finished', 'Finalizado')], default='configuring', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_instances', to='rooms.room')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.player')),
            ],
        ),
        migrations.CreateModel(
            name='GameParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('player', 'Jogador'), ('spectator', 'Espectador')], default='player', max_length=16)),
                ('seat', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='games.gameinstance')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_participations', to='rooms.player')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instance', 'player'), name='unique_player_per_instance')],
            },
        ),
    ]
